#!/usr/bin/env bun
/**
 * 构建「单文件可运行版」：bun build --compile 产物，无需安装包、无需 hutch/Electrobun。
 *
 * 流程：
 * 1. 暂存打包输入（复用 stage.ts：安装依赖、构建前端 web/dist、铺齐 vendor/）
 * 2. 收集内置资源清单（web/dist + prompts + skills + validation，排除 __pycache__）
 * 3. 生成 desktop/portable/generated-assets.ts
 *    （每个文件一个 `with { type: "file" }` 导入，编译时嵌入 exe，运行时按需解压）
 * 4. bun build --compile desktop/portable/launcher.ts → desktop/artifacts/portable/
 *
 * opencode 引擎**不嵌入**（约 142MB）：首次运行由启动器自动下载到数据目录，
 * 或直接复用 exe 同目录 / OPENCODE_BIN 指定的二进制（见 launcher.ts）。
 *
 * 用法：
 *   bun scripts/build-portable.ts                      # 当前宿主平台
 *   bun scripts/build-portable.ts --target=bun-linux-x64   # 交叉编译指定平台
 * 环境变量：OPENCODE_VERSION（启动器首次自动下载的版本，默认 1.18.18）
 */
import { spawnSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { existsSync, mkdirSync, readFileSync, readdirSync, renameSync, rmSync, statSync, writeFileSync } from 'node:fs';
import { dirname, join, relative, sep } from 'node:path';
import { build, type BuildOutput } from 'bun';

const DESKTOP_DIR = join(import.meta.dir, '..'); // desktop/
const REPO_ROOT = dirname(DESKTOP_DIR); // Studio/
const VENDOR = join(DESKTOP_DIR, 'vendor');
const PORTABLE_PKG = join(DESKTOP_DIR, 'portable');
const OUT_DIR = join(DESKTOP_DIR, 'artifacts', 'portable');
const GEN_FILE = join(PORTABLE_PKG, 'generated-assets.ts');

/**
 * 解析编译目标：native -> bun-<当前平台>-<当前架构>；
 * 显式 --target=bun-<os>-<arch> 用于交叉编译。
 * 返回 { target, osLabel, arch, isWindows }。
 */
function resolveTarget(): { target: string; osLabel: string; arch: string; isWindows: boolean } {
  const arg = process.argv.slice(2).find((a) => a.startsWith('--target='))?.split('=')[1];
  let target = arg;
  if (!target || target === 'native') {
    const osLabel = process.platform === 'win32' ? 'windows' : process.platform;
    target = `bun-${osLabel}-${process.arch}`;
  }
  const m = target.match(/^bun-(darwin|linux|windows|win32)-([a-z0-9]+)$/);
  if (!m) throw new Error(`无效的 --target：${target}（示例：bun-darwin-arm64 / bun-darwin-x64 / bun-windows-x64 / bun-linux-x64）`);
  const osRaw = m[1]!;
  const osLabel = osRaw === 'win32' ? 'windows' : osRaw;
  const isWindows = osLabel === 'windows';
  return { target, osLabel, arch: m[2]!, isWindows };
}

function run(command: string, args: string[], cwd: string) {
  console.log(`==> ${command} ${args.join(' ')}（cwd=${cwd}）`);
  const res = spawnSync(command, args, { cwd, stdio: 'inherit' });
  if (res.status !== 0) {
    throw new Error(`命令失败：${command} ${args.join(' ')}（exit=${res.status}）`);
  }
}

/** 递归列出目录内全部文件（绝对路径），排除 __pycache__ / *.pyc */
function listFiles(dir: string, out: string[] = []): string[] {
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    if (entry.name === '__pycache__' || entry.name.endsWith('.pyc')) continue;
    const full = join(dir, entry.name);
    if (entry.isDirectory()) listFiles(full, out);
    else out.push(full);
  }
  return out;
}

/** 内置资源映射：[打包后相对路径, 源文件绝对路径]，相对路径统一用 '/' */
function collectAssets(): Array<{ rel: string; abs: string }> {
  const sources: Array<{ dir: string; relPrefix: string }> = [
    { dir: join(VENDOR, 'web'), relPrefix: 'web' },
    { dir: join(VENDOR, 'server', 'dist'), relPrefix: 'server' },
    { dir: join(VENDOR, 'server', 'prompts'), relPrefix: 'prompts' },
    { dir: join(VENDOR, 'server', 'skills'), relPrefix: 'skills' },
    { dir: join(VENDOR, 'server', 'validation'), relPrefix: 'validation' },
  ];
  const assets: Array<{ rel: string; abs: string }> = [];
  for (const { dir, relPrefix } of sources) {
    if (!existsSync(dir)) throw new Error(`缺少暂存资源（先执行 stage）：${dir}`);
    for (const abs of listFiles(dir)) {
      const rel = `${relPrefix}/${relative(dir, abs).split(sep).join('/')}`;
      assets.push({ rel, abs });
    }
  }
  assets.sort((a, b) => (a.rel < b.rel ? -1 : a.rel > b.rel ? 1 : 0));
  return assets;
}

/** 生成嵌入清单模块（每个文件一个 with { type: "file" } 导入） */
function generateAssetsModule(assets: Array<{ rel: string; abs: string }>, opencodeVersion: string): string {
  const lines: string[] = [
    '// AUTO-GENERATED by desktop/scripts/build-portable.ts — DO NOT EDIT.',
    '// 每个文件在编译期嵌入可执行文件，运行期由启动器解压到数据目录。',
    '',
  ];
  assets.forEach((a, i) => {
    const relImport = `../vendor/${relative(VENDOR, a.abs).split(sep).join('/')}`;
    lines.push(`import a${i} from ${JSON.stringify(relImport)} with { type: "file" };`);
  });
  lines.push('');
  lines.push(`export const BUILD_STAMP = ${JSON.stringify(computeStamp(assets))};`);
  lines.push(`export const OPENCODE_VERSION = ${JSON.stringify(opencodeVersion)};`);
  lines.push('');
  lines.push('export const ASSETS: Array<[relPath: string, embeddedPath: string]> = [');
  assets.forEach((a, i) => lines.push(`  [${JSON.stringify(a.rel)}, a${i}],`));
  lines.push('];');
  lines.push('');
  return lines.join('\n');
}

/** 版本戳：所有文件的 相对路径 + 内容哈希，任何变更都会触发重新解压 */
function computeStamp(assets: Array<{ rel: string; abs: string }>): string {
  const hash = createHash('sha256');
  for (const a of assets) {
    const data = readFileSync(a.abs);
    hash.update(a.rel).update('\0').update(data);
  }
  return hash.digest('hex').slice(0, 16);
}

async function main() {
  // 1. 暂存输入（依赖安装、前端构建、vendor/ 铺齐）
  run('bun', ['scripts/stage.ts'], DESKTOP_DIR);

  // 2. 生成嵌入清单
  const assets = collectAssets();
  const opencodeVersion = (process.env.OPENCODE_VERSION ?? '1.18.18').replace(/^v/, '');
  console.log(`==> 内置资源 ${assets.length} 个文件（约 ${(assets.reduce((s, a) => s + statSync(a.abs).size, 0) / 1024 / 1024).toFixed(2)} MB）`);
  writeFileSync(GEN_FILE, generateAssetsModule(assets, opencodeVersion), 'utf-8');

  // 3. 编译单文件可执行版
  const { target, osLabel, arch, isWindows } = resolveTarget();
  const outName = `UniBotStudio-${osLabel}-${arch}${isWindows ? '.exe' : ''}`;
  console.log(`==> 编译可执行文件（bun build --compile，target=${target} → ${outName}）…`);
  mkdirSync(OUT_DIR, { recursive: true });
  // 注意：Bun.build 的 naming 选项对 compile 产物不生效——产物名固定为入口
  // 文件名（launcher[.exe]），因此这里不传 naming，编译后统一改名为规范名。
  const result: BuildOutput = await build({
    entrypoints: [join(PORTABLE_PKG, 'launcher.ts')],
    outdir: OUT_DIR,
    target,
    compile: true,
    minify: true,
    sourcemap: 'none',
  });
  if (!result.success) {
    console.error(result.logs);
    throw new Error('编译失败');
  }

  // 产物名 = 入口 basename（launcher[.exe]），统一改名为规范名（总是覆盖旧产物）
  const wanted = join(OUT_DIR, outName);
  const produced = [join(OUT_DIR, 'launcher.exe'), join(OUT_DIR, 'launcher')].find((p) => existsSync(p));
  if (existsSync(wanted)) rmSync(wanted, { force: true });
  if (produced && produced !== wanted) renameSync(produced, wanted);
  const size = existsSync(wanted)
    ? (statSync(wanted).size / 1024 / 1024).toFixed(1)
    : '?';
  console.log(`\n==> 构建完成：${wanted}（${size} MB）`);
  console.log(`    opencode 不内置：首次运行自动下载 v${opencodeVersion}（或放 exe 同目录 / 设 OPENCODE_BIN）`);
}

void main();